default:
  interruptible: false
  image: node:lts-alpine3.18
  before_script:
    - apk add chromium
    - export CHROME_BIN='/usr/bin/chromium'
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - pnpm install

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - pnpm run build

test:
  stage: test
  script:
    - pnpm run test:ci
